/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2023-05-04 06:03:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.itwill.model.Contact;

public final class actiontag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.itwill.model.Contact");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\" />\r\n");
      out.write("		<title>JSP</title>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("<h1>JSP Action Tag</h1>\r\n");
      out.write("        ");
 // 스크립트릿에서 자바 객체 생성:
         Contact c1 = new Contact(); 
         
      out.write("<p>\r\n");
      out.write("            c1: ");
      out.print( c1 );
      out.write("<br />\r\n");
      out.write("            c1.id: ");
      out.print( c1.getId() );
      out.write("<br />\r\n");
      out.write("            c1.name: ");
      out.print( c1.getName() );
      out.write("<br />\r\n");
      out.write("            c1.email: ");
      out.print( c1.getEmail() );
      out.write("</p>\r\n");
      out.write("         \r\n");
      out.write("         ");
      com.itwill.model.Contact c2 = null;
      c2 = (com.itwill.model.Contact) _jspx_page_context.getAttribute("c2", jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      if (c2 == null){
        c2 = new com.itwill.model.Contact();
        _jspx_page_context.setAttribute("c2", c2, jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("<p>\r\n");
      out.write("            c2.id: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.itwill.model.Contact)_jspx_page_context.findAttribute("c2")).getId())));
      out.write("<br />\r\n");
      out.write("            c2.name: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.itwill.model.Contact)_jspx_page_context.findAttribute("c2")).getName())));
      out.write("</p>\r\n");
      out.write("         \r\n");
      out.write("         ");

         c1.setName("대한"); 
         
      out.write("<p>\r\n");
      out.write("            c1.name: ");
      out.print( c1.getName() );
      out.write("</p>\r\n");
      out.write("         ");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("c2"), "name", "지대한", null, null, false);
      out.write("<p>\r\n");
      out.write("            c2.name: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.itwill.model.Contact)_jspx_page_context.findAttribute("c2")).getName())));
      out.write("</p>\r\n");
      out.write("         \r\n");
      out.write("         ");

         Contact c3 = new Contact(1, "대한", "01012345678", "daehan@itwill.com");
         
      com.itwill.model.Contact c4 = null;
      c4 = (com.itwill.model.Contact) _jspx_page_context.getAttribute("c4", jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      if (c4 == null){
        c4 = new com.itwill.model.Contact();
        _jspx_page_context.setAttribute("c4", c4, jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("c4"), "id", "1", null, null, false);
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("c4"), "name", "지대한", null, null, false);
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("c4"), "phone", "010-1234-5678", null, null, false);
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("c4"), "email", "daehan@itwill.com", null, null, false);
      }
      out.write("<p>\r\n");
      out.write("            id: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.itwill.model.Contact)_jspx_page_context.findAttribute("c4")).getId())));
      out.write("<br />\r\n");
      out.write("            name: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.itwill.model.Contact)_jspx_page_context.findAttribute("c4")).getName())));
      out.write("<br />\r\n");
      out.write("            phone: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.itwill.model.Contact)_jspx_page_context.findAttribute("c4")).getPhone())));
      out.write("</p>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
