/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2023-05-04 06:07:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.itwill.model.Contact;
import java.util.ArrayList;

public final class scriptlet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.itwill.model.Contact");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\" />\r\n");
      out.write("		<title>JSP</title>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("        <h1>JSP scriptlet 활용</h1>\r\n");
      out.write("        ");
// 테이블을 작성할 더미 데이터 생성:
        ArrayList<Contact> data = new ArrayList<>();  // 빈 리스트를 생성
        for (int i = 0; i < 10; i++) {
            Contact c = new Contact(i, "이름" + i, "전화번호" + i, "이메일" + i);
            data.add(c);
        }
        
      out.write("<table>\r\n");
      out.write("            <caption>연락처</caption>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>No.</th>\r\n");
      out.write("                    <th>이름</th>\r\n");
      out.write("                    <th>전화번호</th>\r\n");
      out.write("                    <th>이메일</th>\r\n");
      out.write("                </tr>                \r\n");
      out.write("            </thead>\r\n");
      out.write("            \r\n");
      out.write("            <tbody>\r\n");
      out.write("            ");

            for (Contact c : data) {
                // JSP 내장객체 out을 사용한 HTML 코드 출력.
                out.print("<tr>");
                out.print("<td>" + c.getId() + "</td>");
                out.print("<td>" + c.getName() + "</td>");
                out.print("<td>" + c.getPhone() + "</td>");
                out.print("<td>" + c.getEmail() + "</td>");                
                out.print("</tr>");
            }
            
      out.write("</tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("		<hr />\r\n");
      out.write("        \r\n");
      out.write("        <h1>scriptlet, expression 활용</h1>\r\n");
      out.write("        \r\n");
      out.write("        <table>\r\n");
      out.write("            <caption>연락처</caption>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>No.</th>\r\n");
      out.write("                    <th>이름</th>\r\n");
      out.write("                    <th>전화번호</th>\r\n");
      out.write("                    <th>이메일</th>\r\n");
      out.write("                </tr>           \r\n");
      out.write("            </thead>\r\n");
      out.write("            \r\n");
      out.write("            <tbody>\r\n");
      out.write("            ");
 for (Contact c : data) { 
      out.write("<tr>\r\n");
      out.write("                    <td>");
      out.print( c.getId() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( c.getName() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( c.getPhone() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( c.getEmail() );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            ");
 } 
      out.write("</tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("        <hr />\r\n");
      out.write("        \r\n");
      out.write("        <h2>Unordered List</h2>\r\n");
      out.write("        ");
      out.write("<ul>\r\n");
      out.write("            ");
 for (Contact c: data) {
      out.write("<li>");
      out.print( c.getName() );
      out.write("</li>                   \r\n");
      out.write("            ");
 } 
      out.write("</ul>\r\n");
      out.write("        \r\n");
      out.write("        <h2>Description List</h2>\r\n");
      out.write("        ");
      out.write("<dl>\r\n");
      out.write("            ");
 for (Contact c : data) { 
      out.write("<dt>");
      out.print( c.getId() );
      out.write("</dt>\r\n");
      out.write("            <dd>");
      out.print( c.getName() );
      out.write("</dd>        \r\n");
      out.write("            <dd>");
      out.print( c.getEmail() );
      out.write("</dd>                            \r\n");
      out.write("            ");
 } 
      out.write("</dl>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
